# Generated by Django 5.2.7 on 2025-10-31 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('photo_path', models.CharField(blank=True, default='', max_length=255)),
                ('faces_detected', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
